### ISSUE TITLE
Look into limelight logic on compbot

### ISSUE THREAD

**Issue by noahlinton** [frc4039/2024#109]
Line 207 of DriveSubsystem.java. We are only looking at the right camera if we do not get a pose from the left camera. I dont think we want to do that. I think we want to update based on both cameras all the time.

Open to input @SteveJacka @Ben-Alderson

**Comment by Ben-Alderson** [comment]
+1
As long as the relative position of the cameras to one-another is correct, using both cameras should only improve the pose estimate.
