### ISSUE TITLE
Update CompBot limelight settings

### ISSUE THREAD

**Issue by noahlinton** [frc4039/2024#119]
Need to tune the position of the camera's using two tags, as well as update the stdDevs

**Comment by noahlinton** [comment]
@Ben-Alderson I think we want too apply a max distance even if we see 2 tags. Right now, we are not doing that so the far tags on the speaker are being trusted event when we drive really far away. 



![Image](https://github.com/frc4039/2024/assets/19657478/8d2ea86b-5d15-4bfc-9610-900495bb411c)

Also, what is the rationale for the formula used for single target scaling distance? Looks like AvgDist^2/30. What does the 30 represent?


![Image](https://github.com/frc4039/2024/assets/19657478/922fa0e4-4194-44d2-a8f9-53cd9cf6c50d)

**Comment by Ben-Alderson** [comment]
The PNP method should be more reliable at long distances. I suspect that's why it's not got a distance limit. Not sure where the 30 comes from. That's just from the example PhotonVision code.

**Comment by noahlinton** [comment]
camera transfers are good. 

Now we need to adjust camera settings to detect tags faster.
