### ISSUE TITLE
Feature-driveToAmpLocation

### ISSUE THREAD

**Issue by noahlinton** [frc4039/2024#125]
While in AMP state, and driver holding left trigger, we currently YAW to the correct Angle. Can we also now translate to the desired pose? 

Based on full field, pose should be -> X:     Y:

**Comment by noahlinton** [comment]
How would we implement this? Would we use a path planner feature? @Ben-Alderson @4039-zach @WyattDube 

I think this is a second event feature, but now that april tags are working better, it might be a simple feature.

**Comment by Ben-Alderson** [comment]
Should be able to leverage PathPlanner for this. Either `AutoBuilder.pathfindToPose` or `AutoBuilder.pathfindThenFollowPath` can be used to generate a path to a position on the fly.

It will try to avoid obstacles marked on the "Navigation Grid" menu of PathPlanner. Right now it looks like there are no obstacles configured.

**Comment by noahlinton** [comment]
Okay I have read through the documentation on path planner. only thing that is unclear is where the code should be. [https://pathplanner.dev/pplib-pathfinding.html](https://pathplanner.dev/pplib-pathfinding.html)

**Comment by Ben-Alderson** [comment]
Probably put the PathConstraints in Constants.java.

`AutoBuilder.pathfindToPose` returns a `Command`, so you can use it anywhere that you use a command. I think you want to replace the TeleopDrive command here.
https://github.com/frc4039/2024/blob/0b7a90a613f09e8e6d9f69b0524aa475f86e3988/src/main/java/frc/robot/RobotContainer.java#L256-L257

**Comment by noahlinton** [comment]
needs to be tested on red side of field to see if the path gets auto flipped or not. Otherwise, feature only works on blue side of the field.
