### ISSUE TITLE
Tune Pivot Motion

### ISSUE THREAD

**Issue by noahlinton** [frc4039/2024#126]
Compbot pivot mechanism is much stiffer. Can we retry tuning the pivot motion to make it faster? 

Update March 26th: We will need to retune the pivot because of the changing weight of the V2 shooter. We should consider new method while doing this.

**Comment by noahlinton** [comment]
@Ben-Alderson do you have comments or suggestions on how to do this? The system is much stiffer than before. Very little to no wobble. Wondering if profiled PID controller makes sense now to get nice acceleration?

**Comment by Ben-Alderson** [comment]
Probably start by widening the voltage limits. Right now the output is capped at 50%.
https://github.com/frc4039/2024/blob/c6383b9da654a0a339c1779211de0dde93288190/src/main/java/frc/robot/Constants.java#L244-L245

Then I would increase the P. Once you have the PID as fast as you're comfortable with, you can start with the motion profile. Since the PID is running on the controller, you should investigate the "motion magic" mode of the Spark Max. Remember that motion profiling will probably not make the motion faster, just less violent.

**Comment by noahlinton** [comment]
@Ben-Alderson can you take a look at this commit and see if you spot any mistakes? I have followed the ["Smart Motion"](https://github.com/REVrobotics/SPARK-MAX-Examples/blob/master/Java/Smart%20Motion%20Example/src/main/java/frc/robot/Robot.java)

https://github.com/frc4039/2024/commit/40b5cffe5fe9ef95ad29ccf6372fd1b85f0d3324

I updated kPivotMicOutput (and max) to 1 instead of 0.5. 

Less violent is what we are looking for. Right now when we speed up pivot, it gets really jerky and lifts the drive base.

**Comment by noahlinton** [comment]
Also, should I remove kD for now?

**Comment by Ben-Alderson** [comment]
Yeah it looks fine to me. I believe units are NOT RPM. I think they'll be degrees/minute for velocity and degrees/minute/second for acceleration.

**Comment by noahlinton** [comment]
Oh okay. Will modify. That's just what the example showed.

**Comment by noahlinton** [comment]
We are fine with current state for Newmarket

**Comment by noahlinton** [comment]
@WyattDube @BlakeMcFadden @Ben-Alderson okay I did some more reading in the ChiefDelphi thread that you guys showed me. You guys had it right. It was a waste of time to go down the path of SmartMotion it seems. My apologies. 

As suggested by Wyatt, we should look into profilled PID controller running on the RIO. Not sure if this changes where we plug the encoder into though.

Also, MotionMagic (which is the other fancy control thing I wanted to try) is only available on CTRE devices, Not REV. 

https://www.chiefdelphi.com/t/understanding-and-tuning-smart-motion-for-an-arm/426639/18

**Comment by Ben-Alderson** [comment]
@noahlinton Is there a reason to turn the motor off? Are you worried about power budget or something?

**Comment by noahlinton** [comment]
To prevent disturbances causing the PID to freak out. When holding travel position, the PID starts to jitter a little. Could probably tune away. My mech-y brain is saying just turn it off once you get there.

Open to more elegant solutions.

On Mar 5, 2024, at 11:19 AM, Ben-Alderson ***@***.***> wrote:

﻿

@noahlinton<https://github.com/noahlinton> Is there a reason to turn the motor off? Are you worried about power budget or something?
