### ISSUE TITLE
Remove limelight feed from shuffleboard

### ISSUE THREAD

**Issue by noahlinton** [frc4039/2024#144]

**Comment by 4039-zach** [comment]
This is manually added to each Driver Station individually, and isn't in the code anywhere.

**Comment by noahlinton** [comment]
@SteveJacka @4039-zach but if we are sending it to the network table, does that still tie up bandwidth? 

Should we just remove from the code and use photonvision web interface via tether if we need to look at the limelights?

**Comment by SteveJacka** [comment]
The stream traffic goes directly from the limelight(server) to the shuffleboard(client).   The network table only contains the url used by the client to access the stream.  As long as no clients (shuffleboard or web browsers) have the stream open, then there is no significant bandwidth consumed.  It's fine to leave the camera server entries in the NT.

**Comment by Ben-Alderson** [comment]
@noahlinton As they said, the limelight feed isn't coming from the code. We do add the "note detection" camera if that's what you're talking about. But the limelight is not something that gets added by the code.

If you are seeing the limelight feed, it's likely there's a [stale entry](https://docs.wpilib.org/en/stable/docs/software/dashboards/smartdashboard/displaying-expressions.html#stale-data) for the camera on the driver station. Try removing the camera from Shuffleboard before connecting to the robot.

**Comment by noahlinton** [comment]
OKay thanks for the clarification everyone! Just wanted to make sure I was on the same page.
