### ISSUE TITLE
Investigate climber motors spark max booting up in wrong direction

### ISSUE THREAD

**Issue by noahlinton** [frc4039/2024#158]
Every now and then, the climber motors start in the wrong direction from what they're expected to.

**Comment by Ben-Alderson** [comment]
@MacPGamesAndApps The [documentation](https://codedocs.revrobotics.com/java/com/revrobotics/cansparkbase#setInverted(boolean)) says that the inversion has no effect in follower mode. But maybe there's some kind of bug. Wouldn't hurt to try not inverting the follower. Also, you probably want to burn the flash on the follower after running follow().

**Comment by Ben-Alderson** [comment]
Are we certain it's the motors spinning different directions? I'm always suspicious of these mechanisms that wind rope onto a spool. Rotating in the same direction can either extend or retract the rope depending on the direction it has been wound.

**Comment by noahlinton** [comment]
burn flash is called after follower mode. Marking as resolved. This is same implementation as pivot mechanism, and it has not run into this problem.
