### ISSUE TITLE
Climb - Snap to Yaw Angle

### ISSUE THREAD

**Issue by noahlinton** [frc4039/2024#183]
Snap yaw to angle - use driver X and B - just adjust the angle and make alliance dependent

**Comment by noahlinton** [comment]
@Ben-Alderson or @WyattDube how does the angle parameter in TeleopDriveCommand work? does it take into account which alliance we are? If we wanted to update the angle to be the two angles for the two climber positions, does that work on both sides of the field?

Thinking Driver B would be stage right and Driver X would be stage left. Wondering if this is simple enough to try at NorthBay to help with aligning to the climber.



![Image](https://github.com/frc4039/2024/assets/19657478/9acdd542-341b-4413-810a-cf7798022ace)

**Comment by ghost** [comment]
Needs tuning at events.
