### ISSUE TITLE
Add Key Metrics

### ISSUE THREAD

**Issue by BlakeMcFadden** [frc4039/2024#205]

**Comment by BlakeMcFadden** [comment]
Looking to add Key metrics to shuffleboard to log in Advantage Scope. Some of these may already be in there just need to be verified

Shooter RPMs
Indexer RPM and requested RPM
Intake RPM
Pivot Angle and Desired Angle
Battery Voltage
Climber RPMs

Please ask if there is anything else you think we should add. Ask @noahlinton  or myself if you have any questions.

**Comment by SteveJacka** [comment]
Just FYI - Intake motor current has been added already yesterday.  We would like to log this as we are using it to stop driving when intaking notes in auto now.

**Comment by ghost** [comment]
Current status:

- [x] Shooter RPMs
- [x] Indexer RPMs
- [x] Intake RPM
- [x] Pivot Angle
- [ ] Pivot Desired Angle (I have an implementation of this that probably doesn't work, and it looks like getReference() has been removed from SPARKPidController)
- [x] Battery Voltage
- [x] Climber RPMs

**Comment by Rain-Alderson** [comment]
@4039-zach Now that we're using a motion profile, you could get the "desired angle" like this:
```java
    public double getDesiredAngle() {
        if (m_goal != null) {
            return m_goal.position;
        } else {
            return -1;
        }
    }
```

**Comment by ghost** [comment]
Thanks Ben!
