### ISSUE TITLE
add note detection to auto's

### ISSUE THREAD

**Issue by noahlinton** [frc4039/2024#56]
We want to move directly towards a note in auto, rather than going to the position we think the NOTE is in. 

How do we implement this? 
We need a command that we can pipe into path planner?

**Comment by SteveJacka** [comment]
I was looking at Path Planner at lunch today, I don't see any way to select paths based on conditions.  i.e. if no note is detected at position C1, instead of the next path being driving back to the speaker scoring position we want to drive directly to note C2.  We don't want to waste time traveling to the speaker and back if we know we don't have the C1 note.    Am I missing something?

**Comment by Ben-Alderson** [comment]
You would need to break up the monolithic auto into one auto for each stage, splitting it up whenever there is a decision.

There would be one auto that is the first part up until the point where the decision needs to happen. At the end of that auto, it would start a NamedCommand. When the named command runs, it will decide between one of two autos depending on if it picked up a note.

e.g.
```java
NamedCommands.registerCommand("StartAuto1Part2",
        new ConditionalCommand(
                AutoBuilder.buildAuto("Auto1 Part2 Yes Note"),
                AutoBuilder.buildAuto("Auto1 Part2 No Note"),
                () -> indexerSubsystem.hasNote()));
```

**Comment by SteveJacka** [comment]
Thanks Ben.  A little messy but makes sense.

**Comment by noahlinton** [comment]
@SteveJacka @maisyt great job getting this feature working on a button press. It sounds like next step is to incorporate into an auto?

**Comment by SteveJacka** [comment]
Started implementing a prototype of this in the Auto2 with Vision Branch.  As per above we built a ParallelRaceCommandGroup that we tested that turns on the intake and drives towards the note.  But looking at pathplanner, I'm not sure we can call a command group as opposed to just a named command.  Ben do youknow if we can call that CommandGroup from Pathplanner instead of build the  the race command group in each path planner auto instead of using the one int he code?

**Comment by SteveJacka** [comment]
@Ben-Alderson interesting behavior I am seeing...    With this Code in robot container.  

        // Auto 2V
        NamedCommands.registerCommand("StartAuto2VPart2",
                new ConditionalCommand(AutoBuilder.buildAuto("Auto2V-Step2a"),
                        AutoBuilder.buildAuto("Auto2V-Step2b"),
                        () -> indexerSubsystem.hasNote()));

        NamedCommands.registerCommand("StartAuto2VPart3",
                new ConditionalCommand(AutoBuilder.buildAuto("Auto2V-Step3a"),
                        AutoBuilder.buildAuto("Auto2V-Step3b"),
                        () -> indexerSubsystem.hasNote()));

The Part 2 works fine but the code in Part 3 doesn't.  Same thing happens for the Auto 3V.  first condition runs fine, the other one doesn't, any thoughts?

**Comment by Ben-Alderson** [comment]
Check your autos. Auto2V-Step2a & Auto2V-Step2b are both incorrect. They should both end by running StartAuto2VPart3.

**Comment by Ben-Alderson** [comment]
@SteveJacka For the auto 3V, Auto3V-Step3a has an error, and Auto3V-Step3b does nothing.

**Comment by SteveJacka** [comment]
@Ben-Alderson Ben I was sure I had updated that...  Can you have a look at auto 3V, it is actually the one I was testing with.

**Comment by Ben-Alderson** [comment]
@SteveJacka Here's what I see on the "Auto2WithVision" branch. Let me know if there's a newer branch I should be looking at.
![image](https://github.com/frc4039/2024/assets/16853778/7efb026a-2a9c-4044-96c0-13e4c5abb316)

**Comment by SteveJacka** [comment]
@Ben-Alderson  I just pushed to Github to ensure you and I are looking at the same.  #V should look like this.  




![Image](https://github.com/frc4039/2024/assets/126035559/74787b8c-7147-4bf3-a5d4-91e66dad8f48)

**Comment by SteveJacka** [comment]
@Ben-Alderson - Did a test when I switched step3 and Step 2, in this case Step3 ran fine this time and Step2 did not.  Looks like consistently the second one does not work for some reason.

**Comment by SteveJacka** [comment]
@Ben-Alderson  just had a successful result, not sure why, trying to sort it out.

**Comment by noahlinton** [comment]
I think simple note detection is done. Conditional is mostly done too. Should we close this issue?

**Comment by SteveJacka** [comment]
I think so.    I would like someone who knows PID control try to help tune the drive to note, this could benefit teleop and auto.  But is probably a separate issue…

**Comment by noahlinton** [comment]
will close and create separate issue
