### ISSUE TITLE
Update Limelight Positions on compbot

### ISSUE THREAD

**Issue by noahlinton** [frc4039/2024#57]

**Comment by noahlinton** [comment]
We have added a second limelight to the back of the robot. The cameras are angled out by 10 degrees. 

We are still trying to tune their position, so the data is not very accurate. We may need to increase the yaw angle even more

@WyattDube @SteveJacka @Ben-Alderson What should we do next to improve this performance?

**Comment by noahlinton** [comment]
Updated tasks:

- [ ] Perform calibration on both limelight camera's - ensure to follow best practices
- [ ] setup infront of target with laser level
- [ ] Check target values coming from photon vision
- [ ] Check pose estimate coming from cameras

**Comment by noahlinton** [comment]
@Ben-Alderson did we apply the instructions here? Looking at 2023 code, it looks like this is different than last year. Specifically, looks like we need to give the limelight the field layout. This is based on our code calling MULTI_TAG_PNP_ON_COPROCESSOR in Vision.java

https://docs.photonvision.org/en/latest/docs/apriltag-pipelines/multitag.html#multitag-localization

**Comment by Ben-Alderson** [comment]
Yes looks like you need to give it a field layout. Perhaps that's why the custom JSON for the practice field didn't work very well. It's another thing we need to remember to reset for events.

**Comment by noahlinton** [comment]
Hmm okay. We will be playing with this on Wednesday at the field. Feels like a black box a little. Hoping we can sort it out.

**Comment by noahlinton** [comment]
![Image](https://github.com/frc4039/2024/assets/19657478/ddcb8af2-ca1a-4207-a364-a70c82e1caff)

**Comment by Ben-Alderson** [comment]
The logic for scaling by distance is already integrated in Vision::getEstimationStdDevs.

The base standard deviation that function uses can be tweaked [here in Constants.java](https://github.com/frc4039/2024/blob/ef1ede6f90ce92e3a1debc0459b7158b121ae252/src/main/java/frc/robot/Constants.java#L285-L286). Larger numbers mean we "trust" the values less. So a bigger number will mean it takes longer for the robot to get to its true position, but it won't jump around as much.

**Comment by noahlinton** [comment]
@Ben-Alderson any advice on how to actually tune these values? I am reading through the classes to understand how they are implemented, and I see we have two cases, single target, and multi target. And I see that if the distance is greater than 4, we use "max values" (Min trust). 

It looks like we could also maybe create a stdDev for use in auto? 

Do we just guess and check these numbers? Do we look for the pose calming down?

**Comment by Ben-Alderson** [comment]
@noahlinton Yeah there's not really an objective method for optimizing these values. I would just mess around with it until it doesn't jump around much but still gets to the real position quickly enough.

Not sure why the stdDev would be different in auto?

**Comment by noahlinton** [comment]
Okay will do! Dont have a reason for being different in auto. Just thinking
